/** Environment configuration. Fails loudly at startup rather than at 3am. */

function required(name: string): string {
  const value = process.env[name]?.trim()
  if (!value) {
    throw new Error(`${name} is required. See bot/README.md.`)
  }
  return value
}

function number(name: string, fallback: number): number {
  const raw = process.env[name]?.trim()
  if (!raw) return fallback
  const value = Number(raw)
  if (!Number.isFinite(value)) throw new Error(`${name} must be a number, got "${raw}"`)
  return value
}

export const config = {
  /** From @BotFather. */
  botToken: required('BOT_TOKEN'),

  /** Origin of the Nuxt layer, e.g. http://web:3000 inside compose. */
  apiBaseUrl: required('API_BASE_URL').replace(/\/+$/, ''),

  /** Shared secret presented to /api/bot/* as X-API-Key. */
  apiKey: required('BOT_API_KEY'),

  /**
   * How the bot waits for the forecast text.
   *
   * The facts arrive in milliseconds and are sent straight away; the prose is
   * generated by a 35B model on one GPU, and under load it queues. These bound
   * how long we keep checking before telling the user to come back.
   */
  pollIntervalMs: number('POLL_INTERVAL_MS', 2_000),
  pollTimeoutMs: number('POLL_TIMEOUT_MS', 180_000),

  /** Request timeout when calling the Nuxt layer. */
  apiTimeoutMs: number('API_TIMEOUT_MS', 30_000),

  /**
   * Proxy for reaching api.telegram.org, where Telegram is blocked.
   *
   * Applied ONLY to Telegram traffic, never to the Nuxt layer. That distinction
   * is the whole point of configuring it here instead of through a global
   * `HTTPS_PROXY`: the API lives at an internal address, and sending internal
   * requests through an external proxy makes them hang until they time out —
   * which, for an inline query, means the picker spins forever.
   *
   * Example: http://user:pass@proxy.example.com:3128 or socks5://127.0.0.1:1080
   */
  telegramProxyUrl: process.env.TELEGRAM_PROXY_URL?.trim() || undefined,
}

export type Config = typeof config
